### ISSUE TITLE
it's detected now by few antiviruses

### ISSUE THREAD

**Issue by ahmedfamhy3** [Bl4ckM1rror/FUD-UUID-Shellcode#6]
https://antiscan.me/scan/new/result?id=RUnNFmGLyCQq
please try to modify the scripts to evade those too
specially node32

**Comment by winterrdog** [comment]
we shall try to counter them even if our primary goal was to evade windows defender. 

anyway thanks for the heads up!

you'll witness some updates soon, we promise.

**Comment by ahmedfamhy3** [comment]
should i try again with the update you did yesterday or no change in detection will happen

**Comment by winterrdog** [comment]
no serious change was made because antiscan.me was temporarily blocking scans but i altered the codebase to make it more evasive. 

so hopefully today

**Comment by winterrdog** [comment]
> should i try again with the update you did yesterday or no change in detection will happen

i made some changes but some antiviruses like [malwarebytes](https://antiscan.me/images/result/0USDB0jVhsis.png) will still detect the executable because of the way the high level Windows API works( AVs can place user-land hooks into the process( heuristic analysis ) and analyze what the malware's doing through proxying API calls to the kernel )

there ways to evade this i am sure but that's an exercise to the users of this code base as we wish to keep the populace of skiddies low so that we can have a bit of order on the internet
